# Codecov configuration for TimeLocker
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 70%          # Overall project coverage target
        threshold: 2%        # Allow 2% decrease
        if_ci_failed: error  # Fail if CI failed
    patch:
      default:
        target: 80%          # New code should have higher coverage
        threshold: 5%        # Allow 5% decrease for patches

  ignore:
    - "tests/"             # Ignore test files
    - "**/__pycache__/"    # Ignore cache directories
    - "**/venv/"           # Ignore virtual environments
    - "**/.venv/"          # Ignore virtual environments

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false   # Comment on all PRs
  require_base: no        # Don't require base commit
  require_head: yes       # Require head commit

flags:
  unittests:
    paths:
      - src/TimeLocker/
