@startuml restic
!pragma useIntermediatePackages false

class restic.Repositories.b2.B2Repository {
  b2_account_id: None
  b2_account_key: None
}
abstract class restic.repository.Repository {
  location: str
  _explicit_password: Optional[str]
  _cached_env: None
}
class restic.errors.RepositoryError {
}
class restic.Repositories.local.LocalRepository {
}
class restic.Repositories.s3.S3Repository {
  aws_access_key_id: None
  aws_secret_access_key: None
  aws_default_region: None
}
class restic.command.CommandBuilder {
  restic_version: None
}
class restic.errors.CommandExecutionError {
  stderr: None
}
class restic.command.ResticCommand {
}
class restic.target.Target {
  selection: FileSelections
  exclusion: FileExclusions
  tags: None
}
class restic.errors.ResticError {
}
class restic.errors.ResticVersionError {
}
class restic.errors.UnsupportedSchemeError {
}
class restic.file_exclusion.FileExclusions {
  patterns: None
}
class restic.file_selection.FileSelections {
  paths: None
}
class restic.restic_client.Restic {
  command_builder: None
  restic_version: None
  repo: Repository
}
class restic.snapshot.Snapshot {
  id: str
  timestamp: str
  paths: list[str]
}
restic.repository.Repository <|-- restic.Repositories.b2.B2Repository
restic.errors.ResticError <|-- restic.errors.RepositoryError
restic.repository.Repository <|-- restic.Repositories.local.LocalRepository
restic.repository.Repository <|-- restic.Repositories.s3.S3Repository
restic.errors.ResticError <|-- restic.errors.CommandExecutionError
restic.target.Target *-- restic.file_selection.FileSelections
restic.target.Target *-- restic.file_exclusion.FileExclusions
restic.errors.ResticError <|-- restic.errors.ResticVersionError
restic.errors.RepositoryError <|-- restic.errors.UnsupportedSchemeError
restic.restic_client.Restic *-- restic.repository.Repository
footer Generated by //py2puml//
@enduml

