"""
Copyright ©  Bruce Cherrington

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

"""
Integration Monitoring and Validation Tools

This module provides integration monitoring and validation tools for continuous
system health assessment, supporting requirement 9.4 of the integration architecture.
"""

import logging
import json
import time
from typing import Dict, Any, Type, TypeVar, Optional, List, Callable, Set, Union
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from pathlib import Path
from enum import Enum
import threading
from collections import defaultdict, deque
import statistics

from ..interfaces.service_interface import ServiceInterface
from ..interfaces.integration_data_models import ServiceContext, Event
from ..interfaces.integration_exceptions import (
    IntegrationMonitoringError,
    ValidationToolError
)
from .service_health_checks import HealthMonitor, HealthCheckResult, HealthStatus
from .service_manager import ServiceManager

logger = logging.getLogger(__name__)

T = TypeVar('T', bound=ServiceInterface)


class MonitoringLevel(Enum):
    """Levels of integration monitoring detail."""
    
    BASIC = "basic"              # Basic service health only
    STANDARD = "standard"        # Health + performance metrics
    DETAILED = "detailed"        # Health + performance + events
    COMPREHENSIVE = "comprehensive"  # All monitoring data


class AlertSeverity(Enum):
    """Severity levels for monitoring alerts."""
    
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class MonitoringMetric:
    """
    A single monitoring metric data point.
    
    This class represents a single measurement of a system metric
    at a specific point in time.
    """
    
    name: str
    value: float
    timestamp: datetime
    unit: str = ""
    tags: Dict[str, str] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class IntegrationAlert:
    """
    Alert generated by integration monitoring.
    
    This class represents an alert condition detected by the
    monitoring system that requires attention.
    """
    
    alert_id: str
    severity: AlertSeverity
    title: str
    description: str
    timestamp: datetime
    
    # Source information
    source_component: str = ""
    source_service: str = ""
    
    # Alert details
    metric_name: str = ""
    metric_value: float = 0.0
    threshold_value: float = 0.0
    
    # Resolution information
    resolved: bool = False
    resolved_timestamp: Optional[datetime] = None
    resolution_notes: str = ""
    
    # Additional context
    tags: Dict[str, str] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SystemHealthSnapshot:
    """
    Snapshot of overall system health at a point in time.
    
    This class captures the complete health state of the system
    including all services and integration points.
    """
    
    timestamp: datetime
    overall_status: HealthStatus
    
    # Service health
    service_count: int = 0
    healthy_services: int = 0
    degraded_services: int = 0
    unhealthy_services: int = 0
    
    # Performance metrics
    average_response_time_ms: float = 0.0
    total_throughput_ops_per_sec: float = 0.0
    
    # Event statistics
    events_published_per_minute: float = 0.0
    events_processed_per_minute: float = 0.0
    
    # Error statistics
    error_rate_per_minute: float = 0.0
    critical_errors_count: int = 0
    
    # Resource usage
    cpu_usage_percent: float = 0.0
    memory_usage_percent: float = 0.0
    
    # Active alerts
    active_alerts_count: int = 0
    critical_alerts_count: int = 0
    
    # Additional metrics
    custom_metrics: Dict[str, float] = field(default_factory=dict)


class MetricsCollector:
    """
    Collector for system and service metrics.
    
    This class collects various metrics from services and system
    components for monitoring and analysis purposes.
    """
    
    def __init__(self, retention_hours: int = 24):
        """
        Initialize metrics collector.
        
        Args:
            retention_hours: How long to retain metrics data
        """
        self.retention_hours = retention_hours
        self.metrics: Dict[str, deque] = defaultdict(lambda: deque(maxlen=10000))
        self.lock = threading.RLock()
        
        logger.debug("Created metrics collector")
    
    def record_metric(self, metric: MonitoringMetric) -> None:
        """
        Record a metric data point.
        
        Args:
            metric: Metric to record
        """
        with self.lock:
            self.metrics[metric.name].append(metric)
            self._cleanup_old_metrics()
    
    def record_value(self, 
                    name: str, 
                    value: float, 
                    unit: str = "",
                    tags: Dict[str, str] = None,
                    metadata: Dict[str, Any] = None) -> None:
        """
        Record a metric value with current timestamp.
        
        Args:
            name: Metric name
            value: Metric value
            unit: Unit of measurement
            tags: Optional tags for the metric
            metadata: Optional metadata
        """
        metric = MonitoringMetric(
            name=name,
            value=value,
            timestamp=datetime.now(),
            unit=unit,
            tags=tags or {},
            metadata=metadata or {}
        )
        self.record_metric(metric)
    
    def get_metric_values(self, 
                         name: str, 
                         since: datetime = None,
                         limit: int = None) -> List[MonitoringMetric]:
        """
        Get metric values for a specific metric.
        
        Args:
            name: Metric name
            since: Only return values after this timestamp
            limit: Maximum number of values to return
            
        Returns:
            List of metric values
        """
        with self.lock:
            if name not in self.metrics:
                return []
            
            values = list(self.metrics[name])
            
            # Filter by timestamp if specified
            if since is not None:
                values = [m for m in values if m.timestamp >= since]
            
            # Apply limit if specified
            if limit is not None:
                values = values[-limit:]
            
            return values
    
    def get_metric_statistics(self, 
                            name: str, 
                            since: datetime = None) -> Dict[str, float]:
        """
        Get statistical summary for a metric.
        
        Args:
            name: Metric name
            since: Only include values after this timestamp
            
        Returns:
            Dictionary with statistical information
        """
        values = self.get_metric_values(name, since)
        
        if not values:
            return {}
        
        numeric_values = [m.value for m in values]
        
        return {
            'count': len(numeric_values),
            'min': min(numeric_values),
            'max': max(numeric_values),
            'mean': statistics.mean(numeric_values),
            'median': statistics.median(numeric_values),
            'stdev': statistics.stdev(numeric_values) if len(numeric_values) > 1 else 0.0,
            'latest': numeric_values[-1] if numeric_values else 0.0,
            'first_timestamp': values[0].timestamp.isoformat(),
            'latest_timestamp': values[-1].timestamp.isoformat()
        }
    
    def get_all_metric_names(self) -> List[str]:
        """
        Get names of all recorded metrics.
        
        Returns:
            List of metric names
        """
        with self.lock:
            return list(self.metrics.keys())
    
    def _cleanup_old_metrics(self) -> None:
        """
        Remove metrics older than retention period.
        """
        cutoff_time = datetime.now() - timedelta(hours=self.retention_hours)
        
        for metric_name, metric_deque in self.metrics.items():
            # Remove old metrics from the front of the deque
            while metric_deque and metric_deque[0].timestamp < cutoff_time:
                metric_deque.popleft()


class AlertManager:
    """
    Manager for integration monitoring alerts.
    
    This class manages the lifecycle of alerts including creation,
    escalation, and resolution tracking.
    """
    
    def __init__(self, max_alerts: int = 1000):
        """
        Initialize alert manager.
        
        Args:
            max_alerts: Maximum number of alerts to retain
        """
        self.max_alerts = max_alerts
        self.alerts: Dict[str, IntegrationAlert] = {}
        self.alert_handlers: List[Callable[[IntegrationAlert], None]] = []
        self.lock = threading.RLock()
        
        logger.debug("Created alert manager")
    
    def create_alert(self, 
                    severity: AlertSeverity,
                    title: str,
                    description: str,
                    source_component: str = "",
                    source_service: str = "",
                    metric_name: str = "",
                    metric_value: float = 0.0,
                    threshold_value: float = 0.0,
                    tags: Dict[str, str] = None,
                    metadata: Dict[str, Any] = None) -> IntegrationAlert:
        """
        Create a new alert.
        
        Args:
            severity: Alert severity level
            title: Alert title
            description: Alert description
            source_component: Component that generated the alert
            source_service: Service that generated the alert
            metric_name: Name of metric that triggered alert
            metric_value: Current value of the metric
            threshold_value: Threshold value that was exceeded
            tags: Optional tags for the alert
            metadata: Optional metadata
            
        Returns:
            Created alert
        """
        import uuid
        
        alert_id = f"alert_{uuid.uuid4().hex[:8]}"
        
        alert = IntegrationAlert(
            alert_id=alert_id,
            severity=severity,
            title=title,
            description=description,
            timestamp=datetime.now(),
            source_component=source_component,
            source_service=source_service,
            metric_name=metric_name,
            metric_value=metric_value,
            threshold_value=threshold_value,
            tags=tags or {},
            metadata=metadata or {}
        )
        
        with self.lock:
            self.alerts[alert_id] = alert
            
            # Cleanup old alerts if we exceed the limit
            if len(self.alerts) > self.max_alerts:
                self._cleanup_old_alerts()
        
        # Notify alert handlers
        for handler in self.alert_handlers:
            try:
                handler(alert)
            except Exception as e:
                logger.error(f"Error in alert handler: {e}")
        
        logger.warning(f"Created {severity.value} alert: {title}")
        return alert
    
    def resolve_alert(self, alert_id: str, resolution_notes: str = "") -> bool:
        """
        Resolve an alert.
        
        Args:
            alert_id: ID of alert to resolve
            resolution_notes: Optional notes about the resolution
            
        Returns:
            True if alert was resolved, False if not found
        """
        with self.lock:
            if alert_id in self.alerts:
                alert = self.alerts[alert_id]
                alert.resolved = True
                alert.resolved_timestamp = datetime.now()
                alert.resolution_notes = resolution_notes
                
                logger.info(f"Resolved alert {alert_id}: {alert.title}")
                return True
            
            return False
    
    def get_active_alerts(self, severity: AlertSeverity = None) -> List[IntegrationAlert]:
        """
        Get list of active (unresolved) alerts.
        
        Args:
            severity: Optional severity filter
            
        Returns:
            List of active alerts
        """
        with self.lock:
            active_alerts = [alert for alert in self.alerts.values() if not alert.resolved]
            
            if severity is not None:
                active_alerts = [alert for alert in active_alerts if alert.severity == severity]
            
            # Sort by timestamp (newest first)
            active_alerts.sort(key=lambda a: a.timestamp, reverse=True)
            
            return active_alerts
    
    def get_alert_summary(self) -> Dict[str, Any]:
        """
        Get summary of alert statistics.
        
        Returns:
            Dictionary with alert summary information
        """
        with self.lock:
            total_alerts = len(self.alerts)
            active_alerts = [alert for alert in self.alerts.values() if not alert.resolved]
            
            severity_counts = defaultdict(int)
            for alert in active_alerts:
                severity_counts[alert.severity.value] += 1
            
            return {
                'total_alerts': total_alerts,
                'active_alerts': len(active_alerts),
                'resolved_alerts': total_alerts - len(active_alerts),
                'severity_breakdown': dict(severity_counts),
                'critical_alerts': severity_counts[AlertSeverity.CRITICAL.value],
                'error_alerts': severity_counts[AlertSeverity.ERROR.value],
                'warning_alerts': severity_counts[AlertSeverity.WARNING.value],
                'info_alerts': severity_counts[AlertSeverity.INFO.value]
            }
    
    def add_alert_handler(self, handler: Callable[[IntegrationAlert], None]) -> None:
        """
        Add handler for new alerts.
        
        Args:
            handler: Function to call when new alerts are created
        """
        self.alert_handlers.append(handler)
    
    def _cleanup_old_alerts(self) -> None:
        """
        Remove old resolved alerts to prevent memory growth.
        """
        # Keep only the most recent alerts
        all_alerts = list(self.alerts.values())
        all_alerts.sort(key=lambda a: a.timestamp, reverse=True)
        
        # Keep all unresolved alerts plus most recent resolved alerts
        alerts_to_keep = []
        resolved_count = 0
        
        for alert in all_alerts:
            if not alert.resolved:
                alerts_to_keep.append(alert)
            elif resolved_count < self.max_alerts // 2:  # Keep half for resolved
                alerts_to_keep.append(alert)
                resolved_count += 1
        
        # Update alerts dictionary
        self.alerts = {alert.alert_id: alert for alert in alerts_to_keep}


class IntegrationMonitor:
    """
    Comprehensive integration monitoring system.
    
    This class provides continuous monitoring of service integration
    health, performance, and system-wide metrics with alerting capabilities.
    """
    
    def __init__(self, 
                 service_manager: ServiceManager,
                 monitoring_level: MonitoringLevel = MonitoringLevel.STANDARD,
                 data_retention_hours: int = 24):
        """
        Initialize integration monitor.
        
        Args:
            service_manager: ServiceManager to monitor
            monitoring_level: Level of monitoring detail
            data_retention_hours: How long to retain monitoring data
        """
        self.service_manager = service_manager
        self.monitoring_level = monitoring_level
        self.data_retention_hours = data_retention_hours
        
        # Monitoring components
        self.health_monitor = HealthMonitor()
        self.metrics_collector = MetricsCollector(data_retention_hours)
        self.alert_manager = AlertManager()
        
        # Monitoring state
        self.monitoring_active = False
        self.monitor_thread: Optional[threading.Thread] = None
        self.check_interval_seconds = 30.0
        
        # Health snapshots
        self.health_snapshots: deque = deque(maxlen=1000)
        
        # Event tracking (if detailed monitoring)
        self.event_statistics: Dict[str, int] = defaultdict(int)
        self.last_event_stats_reset = datetime.now()
        
        # Setup alert handlers
        self.alert_manager.add_alert_handler(self._log_alert)
        
        logger.info(f"Created integration monitor with {monitoring_level.value} level")
    
    def start_monitoring(self) -> None:
        """
        Start continuous integration monitoring.
        """
        if self.monitoring_active:
            logger.warning("Integration monitoring is already active")
            return
        
        # Add all services from service manager to health monitor
        service_status = self.service_manager.get_service_status()
        for service_name, status in service_status.items():
            if status.get('initialized', False):
                try:
                    service = self.service_manager.get_service_by_name(service_name)
                    self.health_monitor.add_service(service)
                except Exception as e:
                    logger.warning(f"Could not add service {service_name} to health monitor: {e}")
        
        # Start health monitoring
        self.health_monitor.start_monitoring()
        
        # Start integration monitoring
        self.monitoring_active = True
        self.monitor_thread = threading.Thread(target=self._monitoring_loop, daemon=True)
        self.monitor_thread.start()
        
        # Setup event monitoring if detailed level
        if self.monitoring_level in [MonitoringLevel.DETAILED, MonitoringLevel.COMPREHENSIVE]:
            self._setup_event_monitoring()
        
        logger.info("Started integration monitoring")
    
    def stop_monitoring(self) -> None:
        """
        Stop continuous integration monitoring.
        """
        if not self.monitoring_active:
            return
        
        self.monitoring_active = False
        
        # Stop health monitoring
        self.health_monitor.stop_monitoring()
        
        # Stop integration monitoring thread
        if self.monitor_thread is not None:
            self.monitor_thread.join(timeout=5.0)
        
        logger.info("Stopped integration monitoring")
    
    def get_system_health_snapshot(self) -> SystemHealthSnapshot:
        """
        Get current system health snapshot.
        
        Returns:
            Current system health snapshot
        """
        timestamp = datetime.now()
        
        # Get service health information
        health_dashboard = self.health_monitor.get_health_dashboard()
        
        service_count = health_dashboard.get('total_services', 0)
        healthy_services = health_dashboard.get('healthy_services', 0)
        
        # Calculate degraded and unhealthy services
        service_status = health_dashboard.get('service_status', {})
        degraded_services = sum(1 for status in service_status.values() 
                              if status.get('last_status') == HealthStatus.DEGRADED.value)
        unhealthy_services = service_count - healthy_services - degraded_services
        
        # Determine overall status
        if unhealthy_services > 0:
            overall_status = HealthStatus.UNHEALTHY
        elif degraded_services > 0:
            overall_status = HealthStatus.DEGRADED
        elif healthy_services == service_count and service_count > 0:
            overall_status = HealthStatus.HEALTHY
        else:
            overall_status = HealthStatus.UNKNOWN
        
        # Get performance metrics
        avg_response_time = health_dashboard.get('average_response_time_ms', 0.0)
        
        # Get event statistics
        events_per_minute = self._calculate_events_per_minute()
        
        # Get error statistics
        error_rate = self._calculate_error_rate()
        
        # Get alert statistics
        alert_summary = self.alert_manager.get_alert_summary()
        
        snapshot = SystemHealthSnapshot(
            timestamp=timestamp,
            overall_status=overall_status,
            service_count=service_count,
            healthy_services=healthy_services,
            degraded_services=degraded_services,
            unhealthy_services=unhealthy_services,
            average_response_time_ms=avg_response_time,
            events_published_per_minute=events_per_minute.get('published', 0.0),
            events_processed_per_minute=events_per_minute.get('processed', 0.0),
            error_rate_per_minute=error_rate,
            active_alerts_count=alert_summary.get('active_alerts', 0),
            critical_alerts_count=alert_summary.get('critical_alerts', 0)
        )
        
        # Add custom metrics if comprehensive monitoring
        if self.monitoring_level == MonitoringLevel.COMPREHENSIVE:
            snapshot.custom_metrics = self._collect_custom_metrics()
        
        # Store snapshot
        self.health_snapshots.append(snapshot)
        
        return snapshot
    
    def get_monitoring_dashboard(self) -> Dict[str, Any]:
        """
        Get comprehensive monitoring dashboard data.
        
        Returns:
            Dictionary with monitoring dashboard information
        """
        current_snapshot = self.get_system_health_snapshot()
        
        # Get recent trends
        recent_snapshots = [s for s in self.health_snapshots 
                          if s.timestamp > datetime.now() - timedelta(hours=1)]
        
        # Calculate trends
        trends = self._calculate_health_trends(recent_snapshots)
        
        # Get top metrics
        top_metrics = self._get_top_metrics()
        
        # Get recent alerts
        recent_alerts = self.alert_manager.get_active_alerts()[:10]  # Top 10
        
        return {
            'monitoring_active': self.monitoring_active,
            'monitoring_level': self.monitoring_level.value,
            'current_health': asdict(current_snapshot),
            'health_trends': trends,
            'top_metrics': top_metrics,
            'recent_alerts': [asdict(alert) for alert in recent_alerts],
            'alert_summary': self.alert_manager.get_alert_summary(),
            'health_dashboard': self.health_monitor.get_health_dashboard(),
            'total_snapshots': len(self.health_snapshots)
        }
    
    def create_performance_alert(self, 
                               service_name: str,
                               metric_name: str,
                               current_value: float,
                               threshold: float) -> IntegrationAlert:
        """
        Create a performance-related alert.
        
        Args:
            service_name: Name of the service
            metric_name: Name of the performance metric
            current_value: Current value of the metric
            threshold: Threshold that was exceeded
            
        Returns:
            Created alert
        """
        severity = AlertSeverity.WARNING
        if current_value > threshold * 2:
            severity = AlertSeverity.ERROR
        if current_value > threshold * 5:
            severity = AlertSeverity.CRITICAL
        
        return self.alert_manager.create_alert(
            severity=severity,
            title=f"Performance degradation in {service_name}",
            description=f"{metric_name} is {current_value:.2f}, exceeding threshold of {threshold:.2f}",
            source_component="IntegrationMonitor",
            source_service=service_name,
            metric_name=metric_name,
            metric_value=current_value,
            threshold_value=threshold,
            tags={"type": "performance", "service": service_name}
        )
    
    def export_monitoring_data(self, output_path: Path) -> None:
        """
        Export monitoring data to file for analysis.
        
        Args:
            output_path: Path to export data to
        """
        try:
            export_data = {
                'export_timestamp': datetime.now().isoformat(),
                'monitoring_level': self.monitoring_level.value,
                'health_snapshots': [asdict(snapshot) for snapshot in self.health_snapshots],
                'alert_summary': self.alert_manager.get_alert_summary(),
                'active_alerts': [asdict(alert) for alert in self.alert_manager.get_active_alerts()],
                'metric_names': self.metrics_collector.get_all_metric_names(),
                'metric_statistics': {
                    name: self.metrics_collector.get_metric_statistics(name)
                    for name in self.metrics_collector.get_all_metric_names()
                }
            }
            
            with open(output_path, 'w') as f:
                json.dump(export_data, f, indent=2, default=str)
            
            logger.info(f"Exported monitoring data to {output_path}")
            
        except Exception as e:
            logger.error(f"Failed to export monitoring data: {e}")
            raise IntegrationMonitoringError(f"Export failed: {e}") from e
    
    def _monitoring_loop(self) -> None:
        """
        Main monitoring loop that collects metrics and checks for issues.
        """
        logger.info("Integration monitoring loop started")
        
        while self.monitoring_active:
            try:
                # Collect system health snapshot
                snapshot = self.get_system_health_snapshot()
                
                # Record key metrics
                self.metrics_collector.record_value("system.health_rate", 
                                                   snapshot.healthy_services / max(1, snapshot.service_count))
                self.metrics_collector.record_value("system.response_time_ms", 
                                                   snapshot.average_response_time_ms)
                self.metrics_collector.record_value("system.active_alerts", 
                                                   snapshot.active_alerts_count)
                
                # Check for alert conditions
                self._check_alert_conditions(snapshot)
                
                # Collect service-specific metrics
                if self.monitoring_level in [MonitoringLevel.STANDARD, MonitoringLevel.DETAILED, MonitoringLevel.COMPREHENSIVE]:
                    self._collect_service_metrics()
                
                # Wait for next interval
                time.sleep(self.check_interval_seconds)
                
            except Exception as e:
                logger.error(f"Error in integration monitoring loop: {e}")
                time.sleep(1.0)  # Brief pause before retrying
        
        logger.info("Integration monitoring loop stopped")
    
    def _setup_event_monitoring(self) -> None:
        """
        Setup event monitoring for detailed monitoring levels.
        """
        try:
            event_bus = self.service_manager.get_event_bus()
            
            def event_counter(event: Event):
                self.event_statistics[f"events.{event.event_type}"] += 1
                self.event_statistics["events.total"] += 1
            
            # Subscribe to all events
            event_bus.subscribe_event(
                event_type_pattern=".*",
                handler=event_counter,
                subscriber_name="IntegrationMonitor"
            )
            
            logger.info("Setup event monitoring")
            
        except Exception as e:
            logger.warning(f"Could not setup event monitoring: {e}")
    
    def _calculate_events_per_minute(self) -> Dict[str, float]:
        """
        Calculate events per minute statistics.
        
        Returns:
            Dictionary with event rate statistics
        """
        if self.monitoring_level not in [MonitoringLevel.DETAILED, MonitoringLevel.COMPREHENSIVE]:
            return {'published': 0.0, 'processed': 0.0}
        
        try:
            event_bus = self.service_manager.get_event_bus()
            stats = event_bus.get_statistics()
            
            # Calculate rates based on time since last reset
            time_elapsed = (datetime.now() - self.last_event_stats_reset).total_seconds() / 60.0
            
            if time_elapsed > 0:
                published_rate = stats.get('events_published', 0) / time_elapsed
                processed_rate = stats.get('events_processed', 0) / time_elapsed
            else:
                published_rate = processed_rate = 0.0
            
            return {
                'published': published_rate,
                'processed': processed_rate
            }
            
        except Exception as e:
            logger.warning(f"Could not calculate event rates: {e}")
            return {'published': 0.0, 'processed': 0.0}
    
    def _calculate_error_rate(self) -> float:
        """
        Calculate error rate per minute.
        
        Returns:
            Error rate per minute
        """
        try:
            error_stats = self.service_manager.get_error_statistics()
            
            # Calculate error rate based on recent errors
            recent_errors = error_stats.get('recent_errors', 0)
            time_window_minutes = 5.0  # 5 minute window
            
            return recent_errors / time_window_minutes
            
        except Exception as e:
            logger.warning(f"Could not calculate error rate: {e}")
            return 0.0
    
    def _collect_service_metrics(self) -> None:
        """
        Collect metrics from individual services.
        """
        service_status = self.service_manager.get_service_status()
        
        for service_name, status in service_status.items():
            if not status.get('initialized', False):
                continue
            
            # Record service health
            health_value = 1.0 if status.get('healthy', False) else 0.0
            self.metrics_collector.record_value(
                f"service.{service_name}.health",
                health_value,
                tags={"service": service_name}
            )
            
            # Record service capabilities count
            capabilities_count = len(status.get('capabilities', []))
            self.metrics_collector.record_value(
                f"service.{service_name}.capabilities_count",
                capabilities_count,
                tags={"service": service_name}
            )
    
    def _collect_custom_metrics(self) -> Dict[str, float]:
        """
        Collect custom metrics for comprehensive monitoring.
        
        Returns:
            Dictionary of custom metrics
        """
        custom_metrics = {}
        
        try:
            # Get optimization statistics if available
            if hasattr(self.service_manager, 'get_optimization_statistics'):
                opt_stats = self.service_manager.get_optimization_statistics()
                
                # Extract key optimization metrics
                if 'connection_pools' in opt_stats:
                    pools = opt_stats['connection_pools']
                    custom_metrics['connection_pools.total'] = len(pools)
                    custom_metrics['connection_pools.active'] = sum(
                        pool.get('active_connections', 0) for pool in pools.values()
                    )
                
                if 'async_operations' in opt_stats:
                    async_ops = opt_stats['async_operations']
                    custom_metrics['async_operations.active'] = async_ops.get('active_operations', 0)
                    custom_metrics['async_operations.completed'] = async_ops.get('completed_operations', 0)
        
        except Exception as e:
            logger.warning(f"Could not collect custom metrics: {e}")
        
        return custom_metrics
    
    def _calculate_health_trends(self, snapshots: List[SystemHealthSnapshot]) -> Dict[str, Any]:
        """
        Calculate health trends from recent snapshots.
        
        Args:
            snapshots: List of recent health snapshots
            
        Returns:
            Dictionary with trend information
        """
        if len(snapshots) < 2:
            return {}
        
        # Calculate trends for key metrics
        health_rates = [s.healthy_services / max(1, s.service_count) for s in snapshots]
        response_times = [s.average_response_time_ms for s in snapshots]
        alert_counts = [s.active_alerts_count for s in snapshots]
        
        return {
            'health_rate_trend': self._calculate_trend(health_rates),
            'response_time_trend': self._calculate_trend(response_times),
            'alert_count_trend': self._calculate_trend(alert_counts),
            'snapshots_analyzed': len(snapshots),
            'time_span_minutes': (snapshots[-1].timestamp - snapshots[0].timestamp).total_seconds() / 60.0
        }
    
    def _calculate_trend(self, values: List[float]) -> str:
        """
        Calculate trend direction for a series of values.
        
        Args:
            values: List of numeric values
            
        Returns:
            Trend direction: "improving", "stable", "degrading"
        """
        if len(values) < 2:
            return "stable"
        
        # Simple trend calculation based on first and last values
        first_half = values[:len(values)//2]
        second_half = values[len(values)//2:]
        
        first_avg = sum(first_half) / len(first_half)
        second_avg = sum(second_half) / len(second_half)
        
        change_percent = ((second_avg - first_avg) / max(0.001, first_avg)) * 100
        
        if change_percent > 5:
            return "improving"
        elif change_percent < -5:
            return "degrading"
        else:
            return "stable"
    
    def _get_top_metrics(self) -> Dict[str, Any]:
        """
        Get top metrics for dashboard display.
        
        Returns:
            Dictionary with top metrics
        """
        metric_names = self.metrics_collector.get_all_metric_names()
        
        top_metrics = {}
        for name in metric_names[:10]:  # Top 10 metrics
            stats = self.metrics_collector.get_metric_statistics(name)
            if stats:
                top_metrics[name] = {
                    'latest_value': stats.get('latest', 0.0),
                    'average': stats.get('mean', 0.0),
                    'trend': self._calculate_trend([stats.get('latest', 0.0)])
                }
        
        return top_metrics
    
    def _check_alert_conditions(self, snapshot: SystemHealthSnapshot) -> None:
        """
        Check for conditions that should trigger alerts.
        
        Args:
            snapshot: Current system health snapshot
        """
        # Check overall health rate
        health_rate = snapshot.healthy_services / max(1, snapshot.service_count)
        if health_rate < 0.8:  # Less than 80% healthy
            self.alert_manager.create_alert(
                severity=AlertSeverity.WARNING if health_rate > 0.5 else AlertSeverity.ERROR,
                title="Low system health rate",
                description=f"Only {health_rate:.1%} of services are healthy",
                source_component="IntegrationMonitor",
                metric_name="system.health_rate",
                metric_value=health_rate,
                threshold_value=0.8
            )
        
        # Check response time
        if snapshot.average_response_time_ms > 1000:  # More than 1 second
            self.alert_manager.create_alert(
                severity=AlertSeverity.WARNING,
                title="High system response time",
                description=f"Average response time is {snapshot.average_response_time_ms:.1f}ms",
                source_component="IntegrationMonitor",
                metric_name="system.response_time_ms",
                metric_value=snapshot.average_response_time_ms,
                threshold_value=1000.0
            )
        
        # Check for critical services down
        if snapshot.unhealthy_services > 0:
            self.alert_manager.create_alert(
                severity=AlertSeverity.ERROR,
                title="Services are unhealthy",
                description=f"{snapshot.unhealthy_services} services are currently unhealthy",
                source_component="IntegrationMonitor",
                metric_name="system.unhealthy_services",
                metric_value=snapshot.unhealthy_services,
                threshold_value=0.0
            )
    
    def _log_alert(self, alert: IntegrationAlert) -> None:
        """
        Log alert to system logger.
        
        Args:
            alert: Alert to log
        """
        log_level = {
            AlertSeverity.INFO: logging.INFO,
            AlertSeverity.WARNING: logging.WARNING,
            AlertSeverity.ERROR: logging.ERROR,
            AlertSeverity.CRITICAL: logging.CRITICAL
        }.get(alert.severity, logging.WARNING)
        
        logger.log(log_level, f"ALERT [{alert.severity.value.upper()}] {alert.title}: {alert.description}")


# Convenience functions for integration monitoring

def create_basic_integration_monitor(service_manager: ServiceManager) -> IntegrationMonitor:
    """
    Create a basic integration monitor with standard monitoring level.
    
    Args:
        service_manager: ServiceManager to monitor
        
    Returns:
        Configured IntegrationMonitor
    """
    return IntegrationMonitor(service_manager, MonitoringLevel.STANDARD)


def monitor_integration_temporarily(service_manager: ServiceManager, 
                                  duration_seconds: float = 300.0) -> Dict[str, Any]:
    """
    Monitor integration for a temporary period and return results.
    
    Args:
        service_manager: ServiceManager to monitor
        duration_seconds: How long to monitor (default 5 minutes)
        
    Returns:
        Monitoring results summary
    """
    monitor = create_basic_integration_monitor(service_manager)
    
    try:
        monitor.start_monitoring()
        time.sleep(duration_seconds)
        return monitor.get_monitoring_dashboard()
    finally:
        monitor.stop_monitoring()